[workspace]
members = [
  "esp-idf-hal",
  "app",
]

[profile.dev]
panic = "unwind"

[profile.release]
lto = true
panic = "unwind"
opt-level = "s"

[patch.crates-io]
esp-idf-bindgen = { git = "https://github.com/reitermarkus/esp-idf-bindgen" }
